#!/usr/bin/env python
# -*- coding: utf-8 -*-
# vim: ai ts=4 sts=4 et sw=4 nu

# Note that while the regex tester test Python 2.7 regex idioms,
# the code base itself has been made to be run on host with Python 2.6

try:
    from core import DEBUG, bottle, webbrowser, run, sys, clize
except ImportError:
    from regex_tester.core import DEBUG, bottle, webbrowser, run, sys, clize


@clize
def main(host='localhost', port=9999, debug=DEBUG):
    if debug:
        bottle.debug(True)
        run(host=host, port=port, reloader=True)
    else:
        webbrowser.open('http://%s:%s/' % (host, port))
        run(host=host, port=port)


main(*sys.argv)